flowchart TB
  classDef root fill:#ffe599,stroke:#333,stroke-width:2px;
  classDef collection fill:#d9ead3,stroke:#6aa84f,stroke-width:1px;
  classDef leaf fill:#cfe2f3,stroke:#45818e,stroke-width:1px;
  IIIF2Collection["MDHN's IIIFDexir Collection (82 collections, 32 manifests)"]
  class IIIF2Collection root;
  WilliamsJacksonCollection["Abraham Valentine Williams Jackson Collection (0 collections, 4 manifests)"]
  class WilliamsJacksonCollection collection;
  AdamOleariusCollection["Adam Olearius Collection (0 collections, 6 manifests)"]
  class AdamOleariusCollection collection;
  AlbertGabrielCollection["Albert Gabriel Collection (1 collections, 1 manifests)"]
  class AlbertGabrielCollection collection;
  GabrielOriginalPhotographsCollection["Gabriel Original Photographs Collection (0 collections, 149 manifests)"]
  class GabrielOriginalPhotographsCollection collection;
  AlbertGayetCollection["Albert Gayet (0 collections, 1 manifests)"]
  class AlbertGayetCollection collection;
  AlbertHotzCollection["Albert Hotz Collection (0 collections, 3 manifests)"]
  class AlbertHotzCollection collection;
  SoltykovCollection["Aleksej Soltykov Collection (0 collections, 1 manifests)"]
  class SoltykovCollection collection;
  AndreDaulierCollection["André Daulier Deslandes Collection (0 collections, 2 manifests)"]
  class AndreDaulierCollection collection;
  AndreGodardCollection["Andre Godard Collection (0 collections, 1 manifests)"]
  class AndreGodardCollection collection;
  ArnoldHeimCollection["Arnold Heim Collection (0 collections, 2 manifests)"]
  class ArnoldHeimCollection collection;
  ArsislamicaCollection["Ars Islamica Collection (0 collections, 13 manifests)"]
  class ArsislamicaCollection collection;
  ArthurUphamPopeCollection["Arthur Upham Pope (0 collections, 3 manifests)"]
  class ArthurUphamPopeCollection collection;
  AugusteRacinetCollection["Auguste Racinet (0 collections, 3 manifests)"]
  class AugusteRacinetCollection collection;
  AurelSteinCollection["Aurel Stein (0 collections, 16 manifests)"]
  class AurelSteinCollection collection;
  BenjaminBurgesMooreCollection["Benjamin Burges Moore Collection (0 collections, 3 manifests)"]
  class BenjaminBurgesMooreCollection collection;
  CalligraphyCollection["Calligraphy Collection (2 collections, 4 manifests)"]
  class CalligraphyCollection collection;
  EdinburghOrMS373Collection["Qit‘at-i Khushkhatt Or.MS.373 (0 collections, 74 manifests)"]
  class EdinburghOrMS373Collection collection;
  McGillArabicCollection["McGill Arabic Calligraphy (0 collections, 289 manifests)"]
  class McGillArabicCollection collection;
  CarlaSerenaCollection["Carla Serena Collection (0 collections, 2 manifests)"]
  class CarlaSerenaCollection collection;
  CharlesJamesWillsCollection["Charles James Wills (0 collections, 3 manifests)"]
  class CharlesJamesWillsCollection collection;
  ClaudeAnetCollection["Claude Anet (0 collections, 2 manifests)"]
  class ClaudeAnetCollection collection;
  ClementdeBodeCollection["Clement August DeBode (0 collections, 4 manifests)"]
  class ClementdeBodeCollection collection;
  CornelisDeBruynCollection["Cornelis de Bruyn Collection (0 collections, 6 manifests)"]
  class CornelisDeBruynCollection collection;
  DieulafoyCollection["Dieulafoy Collection (0 collections, 23 manifests)"]
  class DieulafoyCollection collection;
  VideoCollection["Comentary Videos Collection (0 collections, 38 manifests)"]
  class VideoCollection collection;
  EdwardAlexanderPowellCollection["Edward Alexander Powell (0 collections, 2 manifests)"]
  class EdwardAlexanderPowellCollection collection;
  EdwardBrowneCollection["Edward Granville Browne (0 collections, 4 manifests)"]
  class EdwardBrowneCollection collection;
  EdwinLordWeeksCollection["Edwin Lord Weeks (0 collections, 3 manifests)"]
  class EdwinLordWeeksCollection collection;
  EdwardStackCollection["Edward M. Stack (0 collections, 2 manifests)"]
  class EdwardStackCollection collection;
  EdwardScottWaringCollection["Edward Scott Waring (0 collections, 3 manifests)"]
  class EdwardScottWaringCollection collection;
  EllaRebeDurandCollection["Ella Rebe Durand (0 collections, 2 manifests)"]
  class EllaRebeDurandCollection collection;
  EllaSykesCollection["Ella Sykes (0 collections, 3 manifests)"]
  class EllaSykesCollection collection;
  EngelbertKaempferCollection["Engelbert Kaempfer (0 collections, 2 manifests)"]
  class EngelbertKaempferCollection collection;
  ErichSchmidtCollection["Erich F Schmidt Collection (0 collections, 10 manifests)"]
  class ErichSchmidtCollection collection;
  ErnstHerzfeldCollection["Ernst Herzfeld (2 collections, 4 manifests)"]
  class ErnstHerzfeldCollection collection;
  HerzfeldPre_Achaemenian_Pasargadae_Naqsh_RustamIstakhrCollection["Herzfeld's papera and photographs collection (0 collections, 1 manifests)"]
  class HerzfeldPre_Achaemenian_Pasargadae_Naqsh_RustamIstakhrCollection collection;
  HerzfeldPapersCollection["Ernst Herzfeld Papers and Photographs (0 collections, 4 manifests)"]
  class HerzfeldPapersCollection collection;
  ErnstHoeltzerCollection["Ernst Hoeltzer Collection (0 collections, 2 manifests)"]
  class ErnstHoeltzerCollection collection;
  ErnstKuehnelCollection["Ernst Kühnel Collection (0 collections, 1 manifests)"]
  class ErnstKuehnelCollection collection;
  FlandinCosteCollection["Eugene Flandin and Pascal Coste Collection (0 collections, 21 manifests)"]
  class FlandinCosteCollection collection;
  EugenioGaldieriCollection["Eugenio Galdieri (0 collections, 2 manifests)"]
  class EugenioGaldieriCollection collection;
  EustachedeLoreyCollection["Eustache de Lorey (0 collections, 2 manifests)"]
  class EustachedeLoreyCollection collection;
  FatherKrusinskiCollection["Father Krusinski (0 collections, 2 manifests)"]
  class FatherKrusinskiCollection collection;
  FrancisBradleyCollection["Francis Bradley Bradley-Birt (0 collections, 1 manifests)"]
  class FrancisBradleyCollection collection;
  FredericDrewCollection["Frederic Drew Collection (0 collections, 1 manifests)"]
  class FredericDrewCollection collection;
  FriedrichSarreCollection["Friedrich Sarre Collection (0 collections, 8 manifests)"]
  class FriedrichSarreCollection collection;
  GabrielBonvalotCollection["Gabriel Bonvalot (0 collections, 2 manifests)"]
  class GabrielBonvalotCollection collection;
  GaspardDrouvilleCollection["WD: Drouville (0 collections, 2 manifests)"]
  class GaspardDrouvilleCollection collection;
  CurzonCollection["George Nathaniel Curzon Collection (0 collections, 10 manifests)"]
  class CurzonCollection collection;
  GertrudeBellCollection["Gertrude Bell (0 collections, 13 manifests)"]
  class GertrudeBellCollection collection;
  HarfordJonesCollection["Sir Harford Jones Collection (0 collections, 5 manifests)"]
  class HarfordJonesCollection collection;
  HeinrichGlueckCollection["Heinrich Glück Collection (0 collections, 2 manifests)"]
  class HeinrichGlueckCollection collection;
  HarrydeWindtCollection["Harry de Windt Collection (0 collections, 1 manifests)"]
  class HarrydeWindtCollection collection;
  HenrydAllemagneCollection["Henry d'Allemagne Collection (1 collections, 7 manifests)"]
  class HenrydAllemagneCollection collection;
  AllemagnePhotographicCollection["Henry d'Allemagne Collection Photographs (0 collections, 683 manifests)"]
  class AllemagnePhotographicCollection collection;
  HenryFieldCollection["Henry Field Collection (0 collections, 2 manifests)"]
  class HenryFieldCollection collection;
  HenryJamesWhighamCollection["Henry James Whigham (0 collections, 3 manifests)"]
  class HenryJamesWhighamCollection collection;
  HistoryOfTheIranCollection["History of the Iran (0 collections, 3 manifests)"]
  class HistoryOfTheIranCollection collection;
  IsaacAdamsCollection["Isaac Adams (0 collections, 2 manifests)"]
  class IsaacAdamsCollection collection;
  IsaacMalekYonanCollection["Isaac Malek Yonan (0 collections, 2 manifests)"]
  class IsaacMalekYonanCollection collection;
  IsabellaLucyBirdCollection["Isabella Lucy Bird (0 collections, 3 manifests)"]
  class IsabellaLucyBirdCollection collection;
  JamesBaillieFraserCollection["James Baillie Fraser Collection (0 collections, 5 manifests)"]
  class JamesBaillieFraserCollection collection;
  JamesMorierCollection["James Morier Collection (0 collections, 7 manifests)"]
  class JamesMorierCollection collection;
  JeanBaptisteFeuvrierCollection["Jean-Baptiste Feuvrier Collection (0 collections, 8 manifests)"]
  class JeanBaptisteFeuvrierCollection collection;
  ShardinCollection["Jean Chardin Collection (0 collections, 8 manifests)"]
  class ShardinCollection collection;
  JeanDeThevenotCollection["Jean de Thevenot Collection (0 collections, 2 manifests)"]
  class JeanDeThevenotCollection collection;
  JMHoneCollection["J.M Hone Collection (0 collections, 1 manifests)"]
  class JMHoneCollection collection;
  JohnTavernierCollection["John Baptista Tavernier (0 collections, 4 manifests)"]
  class JohnTavernierCollection collection;
  JohnMalcolmCollection["Sir John Malcolm Collection (0 collections, 6 manifests)"]
  class JohnMalcolmCollection collection;
  MalcolmNapierCollection["Malcolm Napier (0 collections, 4 manifests)"]
  class MalcolmNapierCollection collection;
  ManuscriptCollection["Manuscript Collection (7 collections, 0 manifests)"]
  class ManuscriptCollection collection;
  ArabicManuscriptCollection["Arabic Manuscript Collection (0 collections, 16 manifests)"]
  class ArabicManuscriptCollection collection;
  ChristianManuscriptCollection["Christian Manuscript Collection (0 collections, 1 manifests)"]
  class ChristianManuscriptCollection collection;
  DepartedDrawingCollection["Drawing Collection (2 collections, 391 manifests)"]
  class DepartedDrawingCollection collection;
  FalnamaCollection["Falnama (0 collections, 4 manifests)"]
  class FalnamaCollection collection;
  MiscLouisHagheCollection["Louis Haghe and David Roberts Collections (0 collections, 164 manifests)"]
  class MiscLouisHagheCollection collection;
  MuraqqaCollection["Muraqqa (Calligraphy & Painting Collection) (0 collections, 32 manifests)"]
  class MuraqqaCollection collection;
  PersianManuscriptCollection["Persian Manuscript Collection (6 collections, 57 manifests)"]
  class PersianManuscriptCollection collection;
  AbdarRahmanJamiCollection["Abdar Rahman Jami Collection (0 collections, 11 manifests)"]
  class AbdarRahmanJamiCollection collection;
  AmirShahiSabsavariCollection["Amir Shahi Sabsavari Collection (0 collections, 4 manifests)"]
  class AmirShahiSabsavariCollection collection;
  ChronologyofNationsCollection["Asarol Baghie Or.Ms.161 Collection (0 collections, 375 manifests)"]
  class ChronologyofNationsCollection collection;
  KhamseCollection["Nizami Ganjavi Collection (0 collections, 18 manifests)"]
  class KhamseCollection collection;
  SaadiCollection["Saadi Collection (0 collections, 8 manifests)"]
  class SaadiCollection collection;
  ShahnamaCollection["Shahnama Collection (0 collections, 29 manifests)"]
  class ShahnamaCollection collection;
  QuranCollection["Quran Collection (1 collections, 26 manifests)"]
  class QuranCollection collection;
  KufficQuranCollection["Kuffic Quran Collection (0 collections, 16 manifests)"]
  class KufficQuranCollection collection;
  TurkishManuscriptCollection["Turkish Manuscript Collection (0 collections, 24 manifests)"]
  class TurkishManuscriptCollection collection;
  MapCollection["Maps (0 collections, 31 manifests)"]
  class MapCollection collection;
  MaryLeonoraWoulfeSheilCollection["Mary Leonora Woulfe Sheil (0 collections, 1 manifests)"]
  class MaryLeonoraWoulfeSheilCollection collection;
  MaximeSirouxCollection["Maxime Siroux Collection (0 collections, 3 manifests)"]
  class MaximeSirouxCollection collection;
  MiscellaneousCollection["Miscellaneous Collection (5 collections, 8 manifests)"]
  class MiscellaneousCollection collection;
  CatalogsAndIndexCollection["Catalogs And Index (0 collections, 22 manifests)"]
  class CatalogsAndIndexCollection collection;
  DrGhasemGhaniCollection["Dr Ghasem Ghani Collection (0 collections, 801 manifests)"]
  class DrGhasemGhaniCollection collection;
  GolestanPalaceAlbumkhaneCollection["Golestan Palace Albumkhane Collection (4 collections, 1 manifests)"]
  class GolestanPalaceAlbumkhaneCollection collection;
  GPAK0100Collection["Albumkhane 0100 Album (0 collections, 29 manifests)"]
  class GPAK0100Collection collection;
  GPAK0133Collection["Albumkhane 0133 Album (0 collections, 1 manifests)"]
  class GPAK0133Collection collection;
  GPAK0142Collection["Albumkhane 0142 Album (0 collections, 1 manifests)"]
  class GPAK0142Collection collection;
  GPAK0240Collection["Albumkhane 0240 Album (0 collections, 6 manifests)"]
  class GPAK0240Collection collection;
  MiscPhotoAlbumCollection["Photograph Albums (13 collections, 15 manifests)"]
  class MiscPhotoAlbumCollection collection;
  PhototographsOfThePersiaCollection["19 Phototographs Of The Persia (0 collections, 3 manifests)"]
  class PhototographsOfThePersiaCollection collection;
  AbdollahMirzaQajarCollection["Abdollah Mirza Qajar Misc Photo Collection (0 collections, 5 manifests)"]
  class AbdollahMirzaQajarCollection collection;
  AnnemarieSchwarzenbachCollection["Annemarie Schwarzenbach Collection (0 collections, 5 manifests)"]
  class AnnemarieSchwarzenbachCollection collection;
  BementSmithPhotographsCollection["Myron Bement Smith Collection (0 collections, 689 manifests)"]
  class BementSmithPhotographsCollection collection;
  DenisBallySlideCollection["Denis Baly Color Slide Collection (0 collections, 8 manifests)"]
  class DenisBallySlideCollection collection;
  GarthFowdenCollection["Garth Fowden Collection (0 collections, 28 manifests)"]
  class GarthFowdenCollection collection;
  HenryViolletCollection["Henry Viollet Collection (1 collections, 1 manifests)"]
  class HenryViolletCollection collection;
  ViolletOriginalPhotographsCollection["Henry Viollet Original Photographs (0 collections, 914 manifests)"]
  class ViolletOriginalPhotographsCollection collection;
  CreswellPhotographsCollection["Creswell Photographs Collection (0 collections, 2 manifests)"]
  class CreswellPhotographsCollection collection;
  KonstantinVonKaufmanCollection["Konstantin von Kaufman Photographs (0 collections, 89 manifests)"]
  class KonstantinVonKaufmanCollection collection;
  NadarStudioPhotographsCollection["NADAR Studio Photograph Collection (0 collections, 2 manifests)"]
  class NadarStudioPhotographsCollection collection;
  SinglePhotoCollection["Single Photo Collection (0 collections, 21 manifests)"]
  class SinglePhotoCollection collection;
  StephanArpeePhotographsCollection["Stephen Arpee Collection (0 collections, 161 manifests)"]
  class StephanArpeePhotographsCollection collection;
  WisconsinPhotoCollection["Wisconsin Photo Collection (0 collections, 1600 manifests)"]
  class WisconsinPhotoCollection collection;
  MiscReportAndLetterCollection["Report And Letter Collections (0 collections, 18 manifests)"]
  class MiscReportAndLetterCollection collection;
  EtemadOlSaltaneCollection["Mohammad Hasan Khan E'temad os-Saltaneh (0 collections, 11 manifests)"]
  class EtemadOlSaltaneCollection collection;
  NewsMagazineCollection["News Magazine Collection (13 collections, 0 manifests)"]
  class NewsMagazineCollection collection;
  LEMondeIllustreCollection["Le Monde Illustre (0 collections, 5 manifests)"]
  class LEMondeIllustreCollection collection;
  LeJournalillustreCollection["Le Journal illustre (0 collections, 6 manifests)"]
  class LeJournalillustreCollection collection;
  LAssietteauBeurreCollection["L'Assiette au Beurre (0 collections, 1 manifests)"]
  class LAssietteauBeurreCollection collection;
  UnionRepublicaineCollection["L'Union républicaine de la Marne (0 collections, 1 manifests)"]
  class UnionRepublicaineCollection collection;
  LEPetitCollection["Le Petit Journal (0 collections, 5 manifests)"]
  class LEPetitCollection collection;
  LIllustrationCollection["L'Illustration Journal (0 collections, 3 manifests)"]
  class LIllustrationCollection collection;
  IllustrierteWeltschauCollection["Illustrierte Weltschau (0 collections, 1 manifests)"]
  class IllustrierteWeltschauCollection collection;
  NationalGeographyCollection["National Geographic (0 collections, 2 manifests)"]
  class NationalGeographyCollection collection;
  IllustratedLondonNewsCollection["Illustrated London News (0 collections, 35 manifests)"]
  class IllustratedLondonNewsCollection collection;
  LaCiteCollection["La Cite (0 collections, 1 manifests)"]
  class LaCiteCollection collection;
  LIndependantdeBoulognesurMerCollection["L'Indépendant de Boulogne-sur-Mer (0 collections, 1 manifests)"]
  class LIndependantdeBoulognesurMerCollection collection;
  KeyhanCollection["Keyhan Collection (0 collections, 6 manifests)"]
  class KeyhanCollection collection;
  SharafCollection["Sharaf Magazine Collection (0 collections, 1 manifests)"]
  class SharafCollection collection;
  PercySykesCollection["Percy Molesworth Sykes (0 collections, 7 manifests)"]
  class PercySykesCollection collection;
  RobertBlairMunroBinningCollection["Robert Blair Munro Binning Collection (0 collections, 2 manifests)"]
  class RobertBlairMunroBinningCollection collection;
  RobertByronCollection["Robert Byron Collection (4 collections, 1 manifests)"]
  class RobertByronCollection collection;
  ByronPhotographsCollection["Robert Byron's Photograph (0 collections, 1 manifests)"]
  class ByronPhotographsCollection collection;
  ByronSultaniehZanjanCollection["Sultanieh Zanjan (0 collections, 3 manifests)"]
  class ByronSultaniehZanjanCollection collection;
  ByronIsfahanMasjidShahCollection["Masjid-i-Shah (0 collections, 8 manifests)"]
  class ByronIsfahanMasjidShahCollection collection;
  ByronIsfahanMadrassaShahSultanHussainCollection["Isfahan Madrassa of Shah Sultan Hussain (0 collections, 2 manifests)"]
  class ByronIsfahanMadrassaShahSultanHussainCollection collection;
  RobertElliottCollection["Robert Elliott Collection (0 collections, 5 manifests)"]
  class RobertElliottCollection collection;
  RobertKerPorterCollection["Robert Ker Porter (0 collections, 6 manifests)"]
  class RobertKerPorterCollection collection;
  RichardNelsonFryeCollection["Richard Nelson Frye (0 collections, 1 manifests)"]
  class RichardNelsonFryeCollection collection;
  SamuelGrahamWilsonCollection["Samuel Graham Wilson (0 collections, 3 manifests)"]
  class SamuelGrahamWilsonCollection collection;
  SingleSheetEngravingsCollection["Single Sheet Engravings (0 collections, 18 manifests)"]
  class SingleSheetEngravingsCollection collection;
  SvenHedinCollection["Sven Hedin (0 collections, 12 manifests)"]
  class SvenHedinCollection collection;
  ThomasHerbertCollection["Sir Thomas Herbert (0 collections, 2 manifests)"]
  class ThomasHerbertCollection collection;
  MorganShusterCollection["Willim Morgan Shuster Collection (0 collections, 3 manifests)"]
  class MorganShusterCollection collection;
  IIIF2Collection --> WilliamsJacksonCollection
  IIIF2Collection --> AdamOleariusCollection
  IIIF2Collection --> AlbertGabrielCollection
  AlbertGabrielCollection --> GabrielOriginalPhotographsCollection
  IIIF2Collection --> AlbertGayetCollection
  IIIF2Collection --> AlbertHotzCollection
  IIIF2Collection --> SoltykovCollection
  IIIF2Collection --> AndreDaulierCollection
  IIIF2Collection --> AndreGodardCollection
  IIIF2Collection --> ArnoldHeimCollection
  IIIF2Collection --> ArsislamicaCollection
  IIIF2Collection --> ArthurUphamPopeCollection
  IIIF2Collection --> AugusteRacinetCollection
  IIIF2Collection --> AurelSteinCollection
  IIIF2Collection --> BenjaminBurgesMooreCollection
  IIIF2Collection --> CalligraphyCollection
  CalligraphyCollection --> EdinburghOrMS373Collection
  CalligraphyCollection --> McGillArabicCollection
  IIIF2Collection --> CarlaSerenaCollection
  IIIF2Collection --> CharlesJamesWillsCollection
  IIIF2Collection --> ClaudeAnetCollection
  IIIF2Collection --> ClementdeBodeCollection
  IIIF2Collection --> CornelisDeBruynCollection
  IIIF2Collection --> DieulafoyCollection
  IIIF2Collection --> VideoCollection
  IIIF2Collection --> EdwardAlexanderPowellCollection
  IIIF2Collection --> EdwardBrowneCollection
  IIIF2Collection --> EdwinLordWeeksCollection
  IIIF2Collection --> EdwardStackCollection
  IIIF2Collection --> EdwardScottWaringCollection
  IIIF2Collection --> EllaRebeDurandCollection
  IIIF2Collection --> EllaSykesCollection
  IIIF2Collection --> EngelbertKaempferCollection
  IIIF2Collection --> ErichSchmidtCollection
  IIIF2Collection --> ErnstHerzfeldCollection
  ErnstHerzfeldCollection --> HerzfeldPre_Achaemenian_Pasargadae_Naqsh_RustamIstakhrCollection
  ErnstHerzfeldCollection --> HerzfeldPapersCollection
  IIIF2Collection --> ErnstHoeltzerCollection
  IIIF2Collection --> ErnstKuehnelCollection
  IIIF2Collection --> FlandinCosteCollection
  IIIF2Collection --> EugenioGaldieriCollection
  IIIF2Collection --> EustachedeLoreyCollection
  IIIF2Collection --> FatherKrusinskiCollection
  IIIF2Collection --> FrancisBradleyCollection
  IIIF2Collection --> FredericDrewCollection
  IIIF2Collection --> FriedrichSarreCollection
  IIIF2Collection --> GabrielBonvalotCollection
  IIIF2Collection --> GaspardDrouvilleCollection
  IIIF2Collection --> CurzonCollection
  IIIF2Collection --> GertrudeBellCollection
  IIIF2Collection --> HarfordJonesCollection
  IIIF2Collection --> HeinrichGlueckCollection
  IIIF2Collection --> HarrydeWindtCollection
  IIIF2Collection --> HenrydAllemagneCollection
  HenrydAllemagneCollection --> AllemagnePhotographicCollection
  IIIF2Collection --> HenryFieldCollection
  IIIF2Collection --> HenryJamesWhighamCollection
  IIIF2Collection --> HistoryOfTheIranCollection
  IIIF2Collection --> IsaacAdamsCollection
  IIIF2Collection --> IsaacMalekYonanCollection
  IIIF2Collection --> IsabellaLucyBirdCollection
  IIIF2Collection --> JamesBaillieFraserCollection
  IIIF2Collection --> JamesMorierCollection
  IIIF2Collection --> JeanBaptisteFeuvrierCollection
  IIIF2Collection --> ShardinCollection
  IIIF2Collection --> JeanDeThevenotCollection
  IIIF2Collection --> JMHoneCollection
  IIIF2Collection --> JohnTavernierCollection
  IIIF2Collection --> JohnMalcolmCollection
  IIIF2Collection --> MalcolmNapierCollection
  IIIF2Collection --> ManuscriptCollection
  ManuscriptCollection --> ArabicManuscriptCollection
  ManuscriptCollection --> ChristianManuscriptCollection
  ManuscriptCollection --> DepartedDrawingCollection
  DepartedDrawingCollection --> FalnamaCollection
  DepartedDrawingCollection --> MiscLouisHagheCollection
  ManuscriptCollection --> MuraqqaCollection
  ManuscriptCollection --> PersianManuscriptCollection
  PersianManuscriptCollection --> AbdarRahmanJamiCollection
  PersianManuscriptCollection --> AmirShahiSabsavariCollection
  PersianManuscriptCollection --> ChronologyofNationsCollection
  PersianManuscriptCollection --> KhamseCollection
  PersianManuscriptCollection --> SaadiCollection
  PersianManuscriptCollection --> ShahnamaCollection
  ManuscriptCollection --> QuranCollection
  QuranCollection --> KufficQuranCollection
  ManuscriptCollection --> TurkishManuscriptCollection
  IIIF2Collection --> MapCollection
  IIIF2Collection --> MaryLeonoraWoulfeSheilCollection
  IIIF2Collection --> MaximeSirouxCollection
  IIIF2Collection --> MiscellaneousCollection
  MiscellaneousCollection --> CatalogsAndIndexCollection
  MiscellaneousCollection --> DrGhasemGhaniCollection
  MiscellaneousCollection --> GolestanPalaceAlbumkhaneCollection
  GolestanPalaceAlbumkhaneCollection --> GPAK0100Collection
  GolestanPalaceAlbumkhaneCollection --> GPAK0133Collection
  GolestanPalaceAlbumkhaneCollection --> GPAK0142Collection
  GolestanPalaceAlbumkhaneCollection --> GPAK0240Collection
  MiscellaneousCollection --> MiscPhotoAlbumCollection
  MiscPhotoAlbumCollection --> PhototographsOfThePersiaCollection
  MiscPhotoAlbumCollection --> AbdollahMirzaQajarCollection
  MiscPhotoAlbumCollection --> AnnemarieSchwarzenbachCollection
  MiscPhotoAlbumCollection --> BementSmithPhotographsCollection
  MiscPhotoAlbumCollection --> DenisBallySlideCollection
  MiscPhotoAlbumCollection --> GarthFowdenCollection
  MiscPhotoAlbumCollection --> HenryViolletCollection
  HenryViolletCollection --> ViolletOriginalPhotographsCollection
  MiscPhotoAlbumCollection --> CreswellPhotographsCollection
  MiscPhotoAlbumCollection --> KonstantinVonKaufmanCollection
  MiscPhotoAlbumCollection --> NadarStudioPhotographsCollection
  MiscPhotoAlbumCollection --> SinglePhotoCollection
  MiscPhotoAlbumCollection --> StephanArpeePhotographsCollection
  MiscPhotoAlbumCollection --> WisconsinPhotoCollection
  MiscellaneousCollection --> MiscReportAndLetterCollection
  IIIF2Collection --> EtemadOlSaltaneCollection
  IIIF2Collection --> NewsMagazineCollection
  NewsMagazineCollection --> LEMondeIllustreCollection
  NewsMagazineCollection --> LeJournalillustreCollection
  NewsMagazineCollection --> LAssietteauBeurreCollection
  NewsMagazineCollection --> UnionRepublicaineCollection
  NewsMagazineCollection --> LEPetitCollection
  NewsMagazineCollection --> LIllustrationCollection
  NewsMagazineCollection --> IllustrierteWeltschauCollection
  NewsMagazineCollection --> NationalGeographyCollection
  NewsMagazineCollection --> IllustratedLondonNewsCollection
  NewsMagazineCollection --> LaCiteCollection
  NewsMagazineCollection --> LIndependantdeBoulognesurMerCollection
  NewsMagazineCollection --> KeyhanCollection
  NewsMagazineCollection --> SharafCollection
  IIIF2Collection --> PercySykesCollection
  IIIF2Collection --> RobertBlairMunroBinningCollection
  IIIF2Collection --> RobertByronCollection
  RobertByronCollection --> ByronPhotographsCollection
  RobertByronCollection --> ByronSultaniehZanjanCollection
  RobertByronCollection --> ByronIsfahanMasjidShahCollection
  RobertByronCollection --> ByronIsfahanMadrassaShahSultanHussainCollection
  IIIF2Collection --> RobertElliottCollection
  IIIF2Collection --> RobertKerPorterCollection
  IIIF2Collection --> RichardNelsonFryeCollection
  IIIF2Collection --> SamuelGrahamWilsonCollection
  IIIF2Collection --> SingleSheetEngravingsCollection
  IIIF2Collection --> SvenHedinCollection
  IIIF2Collection --> ThomasHerbertCollection
  IIIF2Collection --> MorganShusterCollection
